### ISSUE TITLE
Wherabouts IPV6: Range fails for valid IPv6 format [ fdef:b041:5422:0005::]

### ISSUE THREAD

**Issue by joelcheison** [k8snetworkplumbingwg/whereabouts#293]
**Description**

IPv6 addresses ending with all 0's can be represented in the following format with double semicolon ending
fdef:b041:5422:0005::

However when the same is used in the range config in the whereabouts IPAM NAD, the ipam add function fails.

**Range:**
 "range": "fdef:b041:5422:0005::-fdef:b041:5422:0005:7fff:ffff:ffff:ffff/64" 

**Failure:**
 Warning  FailedCreatePodSandBox  116s (x16 over 2m26s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9c677251030e4fa299cc56b43699c299e437720a1ce9cc73ed61a303460ceba2": plugin type="multus" name="multus-cni-network" failed (add): [efevice-fv-namespace/efevice-fv-20221209-4vxgjbeqnwqpq7gx-d8f6489b7-mp46c:bgf-media-ipv6-net]: error adding container to network "bgf-media-ipv6-net": failed to set up IPAM plugin type "whereabouts": Error at storage engine: OverlappingRangeIPReservation.whereabouts.cni.cncf.io **"fdef-b041-5422-5--" is invalid:** metadata.name: Invalid value: "fdef-b041-5422-5--": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 

Whereas, when providing the starting IP as fdef:b041:5422:0005::**0**, there are no issues.
"range": "fdef:b041:5422:0005::0-fdef:b041:5422:0005:7fff:ffff:ffff:ffff/64" 

**Expected behavior**

fdef:b041:5422:0005:: is a valid IPv6 IP. The expectation is for whereabouts to accept that same as range start.

**To Reproduce**
1. Create a whereabouts IPAM NAD with range with start IP in the following format fdef:b041:5422:0005:: [Ending with double colon]
2.  Create a pod using the NAD
3. Check the kubelet logs for failure

**Environment**:
- Whereabouts version : v0.5.4
- Kubernetes version (use `kubectl version`): v1.25.3
- Network-attachment-definition: 
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bgf-media-ipv6-net
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/br_data
    k8s.v1.cni.cncf.io/nodeSelector: vnf=bgf
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "plugins": [
        {
          "type": "ovs",
          "bridge": "br_data",
          "vlan": 1804,
          "mtu": 9000,
          "ipam": {
            "type": "whereabouts",
            "range": "fdef:b041:5422:0005::-fdef:b041:5422:0005:7fff:ffff:ffff:ffff/64"
          }
        }
      ]
    }
```
- Whereabouts configuration (on the host): N/A
- OS (e.g. from /etc/os-release): 
~> sudo cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
DOCUMENTATION_URL="https://documentation.suse.com/"

- Kernel (e.g. `uname -a`): 
~> uname -a
Linux cp-bm25d3 5.14.21-150400.24.38-default #1 SMP PREEMPT_DYNAMIC Fri Dec 9 09:29:22 UTC 2022 (e9c5676) x86_64 x86_64 x86_64 GNU/Linux

- Others: N/A

**Additional info / context**
Add any other information / context about the problem here.
