### ISSUE TITLE
[BUG] Infinite loop in `install-cni.sh` after 0.8.0

### ISSUE THREAD

**Issue by lubronzhan** [k8snetworkplumbingwg/whereabouts#575]
**Describe the bug**
This was added after 0.8.0 was cut https://github.com/k8snetworkplumbingwg/whereabouts/pull/495
I assume this change was to mimic what openshift was doing to workaround the token not refreshing issue here: https://github.com/openshift/multus-cni/blob/main/images/entrypoint.sh#L502-L508

The problem with whereabouts is that the dockerfile doesn't run `entrypoint.sh` directly, it runs install-cni.sh then ip-control-loop.
```
      - name: whereabouts
        command: [ "/bin/sh" ]
        args:
          - -c
          - >
            SLEEP=false /install-cni.sh &&
            /ip-control-loop -log-level debug
        image: ghcr.io/k8snetworkplumbingwg/whereabouts:latest
```

If the install-cni.sh never exit, ip-controller-loop will never be executed.

**Expected behavior**
Have a background process that update the content of the kubeconfig when running the ip-control-loop.
Or get rid of the kubeconfig in the whereabouts config file, since wherebouts ip-control-loop use client-go InClusterConfig to get service account's token and cert for kubeconfig.

**To Reproduce**
1. 
2. 
3.

**Environment**:
- Whereabouts version : master branch after 0.8.0
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- Whereabouts configuration (on the host): N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
That means the e2e test is not testing enough functionality
https://github.com/k8snetworkplumbingwg/whereabouts/blob/master/hack/e2e-setup-kind-cluster.sh
