### ISSUE TITLE
Duplicate labels when installing via helm controller

### ISSUE THREAD

**Issue by kuttattz** [k8snetworkplumbingwg/whereabouts#620]
**Describe the bug**
I am trying to install whereabouts with [helm controller](https://fluxcd.io/flux/components/helm/). When using flux, it is very important to have no duplicate labels on objects.

Warning  InstallFailed  12s  helm-controller  Helm install failed for release atlantic/whereabouts-chart with chart whereabouts-chart@0.9.0: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 10: mapping key "app" already defined at line 8

```
---
# Source: whereabouts-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-whereabouts-chart
  namespace: kube-system
  labels:
    app: whereabouts                                               <- HERE IS THE ISSUE
    helm.sh/chart: whereabouts-chart-0.9.0
    app: whereabouts-chart                                      <- HERE IS THE ISSUE
    app.kubernetes.io/name: whereabouts-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: whereabouts-chart/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-name-whereabouts-chart
  namespace: kube-system
  labels:
    app: whereabouts                                                             <- HERE IS THE ISSUE
    helm.sh/chart: whereabouts-chart-0.9.0
    app: whereabouts-chart                                                     <- HERE IS THE ISSUE
    app.kubernetes.io/name: whereabouts-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.0"
    app.kubernetes.io/managed-by: Helm
```

**Expected behavior**
The labels must not be duplicated.

**To Reproduce**
1.  Install whereabouts via [helm controller](https://fluxcd.io/flux/components/helm/)
2.  
3.

**Environment**:
- Whereabouts version : 0.9.0
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- Whereabouts configuration (on the host): N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
Add any other information / context about the problem here.
